class EsPartsController < DynamicController
   def initialize()
    @columns_screen=[
                      {order: 3,
                       name: "es_template_id",
                       column_name:"template name",
                       type: "integer",
                       foreign: true, 
                       linked_name: "es_template",
                       model_linked: "EsTemplate",
                       display_new: true,
                       display_edit: true,
                       print: true,
                       link_update: false,
                       search: false,
                       dynamic_filter: true,
                       dynamic_search: true,
                       sort: true
                      },
                      {order: 5,
                       name: "es_template.description",
                       column_name:"template description",
                       type: "string",
                       foreign: false, 
                       linked_name: nil,
                       model_linked: nil,
                       display_new: true,
                       display_edit: true,
                       display_list: true,
                       print: true,
                       link_update: false,
                       search: false,
                       dynamic_filter: false,
                       dynamic_search: false,
                       sort: true
                      },
                      {order: 6,
                       name: "es_template.es_category.name",
                       column_name:"category name",
                       type: "string",
                       foreign: false, 
                       linked_name: nil,
                       model_linked: nil,
                       display_new: true,
                       display_edit: true,
                       display_list: true,
                       print: true,
                       link_update: false,
                       search: false,
                       dynamic_filter: true,
                       dynamic_search: true,
                       sort: true
                      },
                      {order: 7,
                       name: "created_at",
                       column_name:"creation",
                       display_new: true,
                       display_edit: true,
                       display_list: true,
                       search: true,
                       dynamic_filter: true,
                       dynamic_search: true
                      }
                    ]
    super
  end 
end
